# Generated by Django 4.2 on 2025-11-14 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paquetesturisticos', '0002_initial'),
        ('reservas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='detalle_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.detallecliente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='detalle_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.detalleempleado'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.estado'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='paquete_turistico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paquetesturisticos.paqueteturistico'),
        ),
    ]
