# Generated by Django 4.2 on 2025-11-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCreacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=255)),
                ('usuarioDB', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroActividadTablas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_tipo', models.CharField(max_length=255)),
                ('objeto_nombre', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSesiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('hora_sesion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
