# Generated by Django 4.2 on 2025-11-14 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteventasdiarias',
            name='detalle_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.detallecliente'),
        ),
        migrations.AddField(
            model_name='reporteventasdiarias',
            name='detalle_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.detalleempleado'),
        ),
        migrations.AddField(
            model_name='reporteventasdiarias',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.reserva'),
        ),
    ]
