# Generated by Django 4.2 on 2025-11-14 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paquetesturisticos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paqueteturistico',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.detalleempleado'),
        ),
    ]
