# Generated by Django 4.2 on 2025-11-14 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipotransportes', '0001_initial'),
        ('paquetesturisticos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('origen', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_transporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipotransportes.tipotransportes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioTransporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('paquete_turistico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paquetesturisticos.paqueteturistico')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transportes.transporte')),
            ],
        ),
    ]
